version: '3.3'
services:
  database:
    hostname: localhost
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      MSSQL_USER: SA
      MSSQL_SA_PASSWORD: stefanini@123
      ACCEPT_EULA: 1
      MSSQL_PID: Developer
    ports:
      - "5434:1433"
    expose:
      - 5434
  api:
    build: DesafioApi/Desafio
    image: ${DOCKER_REGISTRY-}api
    depends_on:
      - database
    ports:
      - "44397:80"
  angularweb:
    build: DesafioWeb
    depends_on:
      - database
      - api
    ports:
      - "4200:80"
